### ISSUE TITLE
What's the recommended way to make lifetime usage for a circuit available in HA?

### ISSUE THREAD

**Issue by RedwoodForest** [magico13/ha-emporia-vue#159]
I would like to create graphs using the [apex charts card](https://github.com/RomRider/apexcharts-card). The easiest/most flexible way for me to do this would be to base the chart on the lifetime energy consumption and do all the conversion to specific time periods in the chart.

What's the recommended way to make lifetime usage for a circuit available in HA?

One example use case is that I would like to create a bar graph showing 7 days of daily energy usage of my HVAC as well as a line showing the average usage over that time. Here is an example using the monthly usage, which works great now, but will break as soon as the graph includes the end of a month in it:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/1351139/202873547-f74f64dd-2113-483a-98d4-e8cf3f3698aa.png">

```
type: custom:apexcharts-card
apex_config:
  responsive:
    - breakpoint: 769
      options:
        chart:
          height: 500px
    - breakpoint: 1025
      options:
        chart:
          height: 400px
    - breakpoint: 10000
      options:
        chart:
          height: 600px
header:
  show: true
  title: HVAC Energy Usage
  show_states: false
graph_span: 7day
span:
  end: day
  offset: '-1d'
yaxis:
  - id: dailykw
    min: 0
    decimals: 1
    apex_config:
      forceNiceScale: true
      tickAmount: 7
      title:
        text: Usage (kW)
series:
  - entity: sensor.heat_pump_a_c_1_1mon
    type: column
    yaxis_id: dailykw
    name: Daily Usage
    group_by:
      func: diff
      duration: 1day
  - entity: sensor.heat_pump_a_c_1_1mon
    type: line
    yaxis_id: dailykw
    name: Average Daily Usage
    stroke_width: 2
    group_by:
      func: diff
      duration: 7day
    transform: return x / 7
```

I really appreciate all your work on this.
