### ISSUE TITLE
New release of the integration stopped providing 1 minute data.

### ISSUE THREAD

**Issue by rehhoff** [magico13/ha-emporia-vue#212]
The new update stopped providing 1 minute data and now it only supports 1 day and 1 month.
"Realtime" power data in watts can be used to monitor correct operation of electrical motors and pumps.
I have used it to monitor "dry run" of my swimming pool pump to avoid pump seal failure.

Any suggestions to an alternative solution ??

**Comment by huzer1** [comment]
I've had this issue as well for a few versions now. A work around is to remove and re-add.

**Comment by magico13** [comment]
Reloading the integration should be enough to load them without needing to fully remove and readd the whole thing.

**Comment by cobermay** [comment]
The problem is, that I need to reload them all few days - I did not find out if I can trigger the reload with an automation.

**Comment by magico13** [comment]
There's an automation or two in #33 for automatically reloading when that data goes down. I'm going to close this as a duplicate of that issue, just to try to keep things a bit better organized.

I have some ideas I can probably try this weekend to reduce this problem, my longer-term idea is to have the sensors be added dynamically so it's less reliant on the API being fully functional during HA startup but that will probably be a bigger rewrite.

**Comment by cristiangrama** [comment]
This is an automation I have been using and it looks like it's working. Every 15 minutes and on HA startup I reload a single 1min sensor not the whole Emporia integration. It seems to do the trick. The delay of 30 seconds is for the HA start trigger, not sure it's needed but I thought it would not hurt.

```
alias: Emporia 1min sensor fix
description: ""
trigger:
  - platform: time_pattern
    minutes: "15"
    enabled: true
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
    enabled: false
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id: sensor.dehum_water_heater_14_1min
mode: single
```
