### ISSUE TITLE
Only sensor.homevue_123_1min and sensor.homevue_totalusage_1min are working.

### ISSUE THREAD

**Issue by NoSadBeHappy** [magico13/ha-emporia-vue#224]
I didn't update anything, and nothing auto updated, but all of my sensors have stopped giving any data on the minute data point.

Home assistant, one example.
![image](https://github.com/magico13/ha-emporia-vue/assets/95050434/23a6d367-b341-4d72-837c-592ace6d6244)

Prometheus scrape, only two sensors available.
![image](https://github.com/magico13/ha-emporia-vue/assets/95050434/fe7a051e-acdf-4a8f-a431-5f6242f1c13b)

**Comment by NoSadBeHappy** [comment]
Let me know if you need anything else. I am happy to help resolve this issue.

**Comment by NoSadBeHappy** [comment]
Update: after restarting home assistant, it now works as intended. It seems to have all stopped working 10 minutes after midnight yesterday, at least thats when data stopped being recorded by prometheus. I am running home assistant on docker, so let me know what logs I can send to help fix the issue.

**Comment by FredericG-BE** [comment]
I had the same issue: all 1 minute sensors (except for total consumption) were unavailable until I restarted HA.
Thanks for the excellent work!

**Comment by NoSadBeHappy** [comment]
Yeah. Also, quick update, it has still been happening. I have temperarly solved this problem for now by automatically restarting HA every couple days in the middle of the night.

**Comment by matthojo** [comment]
I have found just reloading the integration is enough to get this working again.

**Comment by NoSadBeHappy** [comment]
Thank you, yes I fegured this out recently, forgot to update this issue.

**Comment by chrwei** [comment]
I have the same, or a similar, issue, except it rarely works on startup or restarting HA doesn't fix it.  in fact, restarting is a sure way to trigger it.  Reload does make it work again, and the time it takes to stop working seems rather random.  All I'm seeing in the logs is my automations complaining that the sensor is unavailable

**Comment by sdwhwk** [comment]
I can concur on that. 1min sensors quit working yesterday for me and resetting stopped working completely (for a while that would work). I uninstalled/reinstalled the integration in HACS and HA just a few minutes ago and when it repopulated the sensors, all but the two 1min that the OP stated didn’t. So now all I have are the daily and monthly sensors with minute total and main.

**Comment by NoSadBeHappy** [comment]
@sdwhwk try restarting the integration, and/or HA.

**Comment by sdwhwk** [comment]
That brought them back. Let’s see how long they stay up.

**Comment by chrwei** [comment]
reloading the integration seems to be required after a reboot, and occasionally otherwise, possibly after internet loss?

I added this automation, runs every 15 minutes, keeps it from been unavailable for very long.  

Add/remove/edit the sensors to whichever of yours is most commonly unavailable.  "balance" is the most common for me, but sometimes it's one of the mains instead.  Edit the target sensor too, doesn't matter which one you use, it's just so the reload service can locate the integration.

```
alias: Check Emporia
description: Check Emporia Vue for reload
trigger:
  - platform: time_pattern
    minutes: /15
    enabled: true
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.panel1_123_1min
        state: unavailable
      - condition: state
        entity_id: sensor.panel1_123_1min
        state: unavailable
      - condition: state
        entity_id: sensor.panel_2_balance_1min
        state: unavailable
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id: sensor.panel1_123_1min
mode: single
```
