### ISSUE TITLE
1min sensor

### ISSUE THREAD

**Issue by multinet33** [magico13/ha-emporia-vue#236]
Hello Magico

There is a lot of people facing the 1min sensor that goes offline every time (1d and 1mon are OK).

Do you have a workaround to give us and do you work on a solution ?

thank you

**Comment by magico13** [comment]
Hello, this is a tough one for me because it's not something I can reproduce and so it is not something I can test fixes for. I have started on a rewrite of how startup and polling works in a hope that it will alleviate this issue, or at least make it so that when the sensor stops responding that it automatically comes back up without any user intervention.

I have not had an opportunity to finish those changes so until then all I can recommend is reloading the integration if the sensors drop for a significant amount of time, as that will reset everything back to the start. Short drops in data are to be expected based on the number of errors I have seen from their cloud, even with their app, so the data will never be perfect without reflashing the hardware with a custom firmware.

**Comment by reebgogs** [comment]
I don't know if it helps your troublshooting, but this is what I see when I zoom in on one of these events in Home Assistant History. I am trying to use this to notify me when laundry is done but unfortunately there are too many false positives....

![image](https://github.com/magico13/ha-emporia-vue/assets/144286377/b0cdf863-da46-480e-94c7-9cff25c7870c)

**Comment by magico13** [comment]
My recommendation for alerting on laundry (or anything on a dedicated circuit) is to start the automation when the power usage is more than some value, then add a wait until it drops to 0 for some time. If you only trigger on it going to 0 then you'll have false alerts if your network blips, or if their cloud service blips (which is common). I've been running automations like that for several years now.

**Comment by reebgogs** [comment]
Thanks for the suggestion. Please provide a YAML example of one of those automations.

**Comment by magico13** [comment]
```yaml
alias: Laundry - Dryer Complete
description: ""
trigger:
  - type: power
    platform: device
    device_id: f2582f2dfc4ed5c8ce6391bcaa9347f1
    entity_id: sensor.dryer_2_1min
    domain: sensor
    above: 100
condition: []
action:
  - service: light.turn_on
    target:
      entity_id: light.color_basement
    data:
      color_name: orangered
      brightness_pct: 100
  - wait_for_trigger:
      - type: power
        platform: device
        device_id: f2582f2dfc4ed5c8ce6391bcaa9347f1
        entity_id: sensor.dryer_2_1min
        domain: sensor
        above: -1
        below: 5
        for:
          hours: 0
          minutes: 10
          seconds: 0
    timeout:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
    continue_on_timeout: false
  - device_id: 999fac184eea01586e3af29fb39d6716
    domain: mobile_app
    type: notify
    message: Dryer is done!
    title: Dryer Done
  - service: light.turn_on
    target:
      entity_id: light.color_basement
    data:
      color_name: blue
      brightness_pct: 100
  - service: notify.alexa_media_living_room
    data:
      data:
        type: announce
      message: The dryer is finished.
mode: single
```
