### ISSUE TITLE
12 decimal places

### ISSUE THREAD

**Issue by ifuchs** [magico13/ha-emporia-vue#310]
My Lovelace entities card which shows the 1 minute average for my power monitors is, all of a sudden, showing 12 decimal places for each reading. I am running:
Core 2024.9.1
Supervisor 2024.09.1
Operating System 13.1
Emporia Integration 0.9.3.

**Comment by sekonicpr** [comment]
Having the same issue using Emporia Integration  0.10 in HA 2024.09.2.  Using display precision in sensor setting has not effect.

**Comment by den-mac** [comment]
Happening for me too. Not sure what happened but this is a newly introduced bug.

![Firefox_Screenshot_2024-09-24T00-27-52 622Z](https://github.com/user-attachments/assets/5a8f071f-6a92-4dd5-aa64-eb54567a91ce)

**Comment by den-mac** [comment]
Well I use custom button cards everywhere and they support javascript, so that's my fix :-)

```
      - type: custom:button-card
        entity: sensor.smart_meter_123_1min
        name: |
          [[[
            var raw = (entity.state)
            var power = Math.round(raw * 10) / 10
            return "Meter " + power + " W"
          ]]]
        color: auto
        styles:
          name:
            - font-family: OpenSans-Medium
        template: standard
        show_state: false
        show_name: true
        show_icon: false
        tap_action:
          action: more-info
```

![Firefox_Screenshot_2024-09-24T00-44-21 591Z](https://github.com/user-attachments/assets/19698bf4-c646-4fb4-a772-ec0862dfdf22)
