### ISSUE TITLE
1MIN sensors unavailable after ha first boot.

### ISSUE THREAD

**Issue by russ-sentient** [magico13/ha-emporia-vue#96]
Having an issue where my 1min sensors show as unavailable after a cold reboot of home assistant.  Selecting Reload from the integration menu resolves the issue until next reboot when I have to do it again.

**Comment by magico13** [comment]
This is typically due to errors when calling the API due to some sort of unstableness in their cloud implementation. There's several layers of retry logic built in to try to get around it, both immediate retries and utilizing some features of Home Assistant to do delayed retries but as of right now there's not much I am able to do about it.

If you can get me the logs from after a boot where the entities are showing up as unavailable I can double check that a failed HTTP call to their API is the cause and not something else. I also have plans to try to do more dynamic discovery for entities rather than just at startup and that should hopefully let it find the missing entities again after a minute or two, as of right now if they fail during setup then they won't get rediscovered automatically without a manual reload, as you've found.

**Comment by russ-sentient** [comment]
I have since rebooted a few times and it worked fine.  Next time I catch it happening again I will try to get some logs.  

Thanks for a great integration!  Looking forward to being energy conscious right in Home Assistant.

**Comment by fasavard** [comment]
I do have the same probleme right now, i am at my fifth reboot and i am only able to retreive the total 1MIN of all my sensor, but all of my individual sensor have empty data for the 1MIN

**Comment by fasavard** [comment]
10 time was the charm, it finally showed up

**Comment by maddoxjny** [comment]
My one min becomes unavailable throughout the day.   A reload of the integration fixes the issue.   I was trying to use it to see if the electric heat was on.   Unfortunately, it's too unstable to use.   Thanks for your work on this it's appreciated!

**Comment by happydutch** [comment]
Since a few days, various of the 1 minute metrics are unavailable. Have created an automation that detects it and reload the integration, but there are many times it doesn't work. I do not see anything in error logs that points towards issues. If there is a recommendation how to help to debug, let me know.

**Comment by fasavard** [comment]
Do you have some code to share about your reconnect automatin @happydutch , 
i would happily use it aswell

**Comment by happydutch** [comment]
Hi @fasavard 

Automation:

```
- alias: Emporia Vue Watchdog
  trigger:
    - platform: state
      entity_id: binary_sensor.emporia_vue_health
      from: 'on'
      to: 'off'
      for: 00:10:00
    - platform: time_pattern
      minutes: '/10'
  condition:
    condition: state
    entity_id: binary_sensor.emporia_vue_health
    state: 'off'
  action:
    - service: rest_command.reload_emporia
      data: {}
```

Sensor:
```
- platform: template
  sensors:
    emporia_vue_health:
      friendly_name: "Emporia Vue Health"
      value_template: "{{ (as_timestamp(now()) - as_timestamp(states.sensor.power_fridge_xbox_tv_14_1min.last_changed) < (states('input_number.device_health_threshold')|int)) and (states('sensor.power_fridge_xbox_tv_14_1min') != 'unavailable') }}"
```
You can replace the input number for a hard threshold

```
rest_command:
  reload_emporia:
    url: !secret emporia_url
    method: POST
    headers:
      authorization: !secret rest_api_token
      content-type: 'application/json'
```

emporia_url: https://lakehills.mooo.com/api/config/config_entries/entry/<see below>/reload

Find the hex string (entry_id) in .storage/core.config_entries. Search for emporia_vue

You will need to create a REST API token in the UI.
